version: 0.0
os: windows
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
artifacts:
  files:
    - source: \index.html
    - '**/*'
  base-directory: build